spring:
  data:
    couchbase:
      auto-index: true
  jackson:
    serialization:
      fail-on-empty-beans: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  remove-broken-reference-definitions: false

app:
  couchbase:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    bucket: ${COUCHBASE_BUCKET}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web: debug